sudo apt install kali-desktop-lxde
sudo apt install kali-linux-core
sudo apt install kali-linux-nethunter
sudo apt install kali-desktop-e17
sudo apt install kali-tools-gpu
sudo apt install kali-tools-hardware
sudo apt install kali-tools-crypto-stego
sudo apt install kali-tools-fuzzing
sudo apt install kali-tools-802-11
sudo apt install kali-tools-bluetooth
sudo apt install kali-tools-rfid
sudo apt install kali-tools-sdr
sudo apt install kali-tools-voip
sudo apt install kali-tools-windows-resources
sudo apt install kali-linux-labs
sudo apt install kali-tools-information-gathering
sudo apt install kali-tools-vulnerability
sudo apt install kali-tools-web
sudo apt install kali-tools-database
sudo apt install kali-tools-passwords
sudo apt install kali-tools-wireless
sudo apt install kali-tools-reverse-engineering
sudo apt install kali-tools-exploitation
sudo apt install kali-tools-social-engineering
sudo apt install kali-tools-sniffing-spoofing
sudo apt install kali-tools-post-exploitation
sudo apt install kali-tools-forensics
sudo apt install kali-tools-reporting
sudo apt install kali-linux-large
sudo apt install kali-linux-everything
sudo apt install kali-desktop-live
sudo apt install kali-linux-core
sudo apt install kali-linux-headless
sudo apt install kali-desktop-gnome
sudo apt install kali-desktop-i3
sudo apt install kali-desktop-kde
sudo apt install kali-desktop-lxde
sudo apt install kali-desktop-mate
sudo apt install kali-desktop-xfce
sudo apt install kali-desktop-e17
sudo apt install kali-desktop-core
sudo apt install kali-linux-nethunter
sudo apt install kali-desktop-lxde
sudo apt install kali-linux-core
sudo apt install kali-linux-nethunter
sudo apt install kali-desktop-e17
sudo apt install kali-tools-gpu
sudo apt install kali-tools-hardware
sudo apt install kali-tools-crypto-stego
sudo apt install kali-tools-fuzzing
sudo apt install kali-tools-802-11
sudo apt install kali-tools-bluetooth
sudo apt install kali-tools-rfid
sudo apt install kali-tools-sdr
sudo apt install kali-tools-voip
sudo apt install kali-tools-windows-resources
sudo apt install kali-linux-labs
sudo apt install kali-tools-information-gathering
sudo apt install kali-tools-vulnerability
sudo apt install kali-tools-web
sudo apt install kali-tools-database
sudo apt install kali-tools-passwords
sudo apt install kali-tools-wireless
sudo apt install kali-tools-reverse-engineering
sudo apt install kali-tools-exploitation
sudo apt install kali-tools-social-engineering
sudo apt install kali-tools-sniffing-spoofing
sudo apt install kali-tools-post-exploitation
sudo apt install kali-tools-forensics
sudo apt install kali-tools-reporting
sudo apt install kali-linux-large
sudo apt install kali-linux-everything
sudo apt install kali-desktop-live
sudo apt install kali-linux-core
sudo apt install kali-linux-headless
sudo apt install kali-desktop-gnome
sudo apt install kali-desktop-i3
sudo apt install kali-desktop-kde
sudo apt install kali-desktop-lxde
sudo apt install kali-desktop-mate
sudo apt install kali-desktop-xfce
sudo apt install kali-desktop-e17
sudo apt install kali-desktop-core
sudo apt install kali-linux-nethunter
sudo apt install kali-linux-default
sudo apt update
sudo apt upgred

sudo apt install kali-linux-default
sudo apt update
sudo apt upgred
